[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "pkgconfig==1.5.5",
    "pygame>=2.6.1",
    "timer>=0.3.0",
]
